INSERT INTO public.configuration (application, class, name, value)
VALUES ('SpotifyGateway', 'TelegramSettings', 'IsTokenWorkerMessagesEnabled', 'True'),
       ('SpotifyGateway', 'TelegramSettings', 'IsSearchWorkerMessagesEnabled', 'True'),
       ('SpotifyGateway', 'TelegramSettings', 'IsNewUserAuthenticatedMessagesEnabled', 'True'),
       ('SpotifyGateway', 'BrowseSettings', 'CategoryPlaylistsExpiryHour', '11'),
       ('SpotifyGateway', 'RecommendationSettings', 'KeepUserLocked', 'False'),
       ('SpotifyGateway', 'GeneralSettings', 'LogLevel', 'Warning'),
       ('SpotifyGateway', 'TelegramSettings', 'LogLevel', 'All'),
       ('SpotifyGateway', 'TelegramSettings', 'Token', ''),
       ('SpotifyGateway', 'TelegramSettings', 'ErrorLogChatId', ''),
       ('SpotifyGateway', 'TelegramSettings', 'InformationChatId', ''),
       ('SpotifyGateway', 'GeneralSettings', 'SpotifyPlaylistUrl', 'https://open.spotify.com/playlist/'),
       ('SpotifyGateway', 'RecommendationSettings', 'IsAlbumSearchEnabled', 'True'),
       ('SpotifyGateway', 'AuthSettings', 'HangfireToken', 'HangfireToken'),
       ('SpotifyGateway', 'AuthSettings', 'SwaggerToken', 'SwaggerToken'),
       ('SpotifyGateway', 'AuthSettings', 'AdminToken', 'AdminToken'),
       ('SpotifyGateway', 'GeneralSettings', 'IsSearchWorkerEnabled', 'False'),
       ('Prediction', 'GeneralSettings', 'Global', '{"EnabledMethods": ["IsolationForest"]}'),
       ('SpotifyGateway', 'AuthSettings', 'SessionKey', ''),
       ('SpotifyGateway', 'AuthSettings', 'TokenKey', ''),
       ('SpotifyGateway', 'GeneralSettings', 'AdFrequency', '6');